// Generated by Scripts/update-codex-protocol from codex-protocol.lock.json.
// Do not edit; regenerate via the script. CodexProtocolLockTests asserts
// these values stay identical to the vendored lock.

public enum CodexProtocolLockSnapshot {
	public static let schemaTargetCliVersion = "0.144.6"
	public static let sourceBinarySha256 = "80a3933d11a9d13ef806aa24f7bb8afc9169cfe4e9b09d6da6a92922cbde9cff"
}
